### ISSUE TITLE
How do you think about using rxlifecycle navi library for safe request?

### ISSUE THREAD

**Issue by leeyc09** [teegarcs/RetroRx#1]
It's more easy,isn't it?

**Comment by teegarcs** [comment]
Hi @leeyc09 , you are correct. You could easily include this util lib to avoid having to call unsubscribe() in your view's onPause/onDestroy.  I think that it is up to you and what you desire in your implementation on whether you would want to include this or not. For the purposes of my demo application, I wanted to make it clear to the reader what we need to do with any live subscription thus exposing these methods in my View. I hope that clears it up. 

Here is a link to the mentioned lib: https://github.com/trello/RxLifecycle

**Comment by leeyc09** [comment]
Thank you so much.
